name: Deploy Backend to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Check out the code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust this version if you need another Java version
          distribution: 'temurin'

      # Build the .jar file using Maven
      - name: Build the application
        run: mvn clean install

      # Set up SSH key for connecting to EC2
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      # Copy the newly built .jar file to the EC2 instance
      - name: Copy .jar file to EC2
        run: |
          scp -i ec2_key.pem target/FYPBack-1.0-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/FYPBack-1.0-SNAPSHOT.jar

      # Restart the backend service on the EC2 instance
      - name: Restart backend service on EC2
        run: |
          ssh -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart backend"
